### ISSUE TITLE
Enable Auto-pairing for common markdown chars

### ISSUE THREAD

**Issue by eksperimental** [elixir-editors/elixir-tmbundle#101]
I find this a missing feature when I need to use backticks around code.
Also i think I could be useful to add support for `*` and `_`

I have tried adding to `Typing Pairs.tmPreferences`
but it didn't work...any idea why?

``` xml
            <array>
                <string>`</string>
                <string>`</string>
            </array>
            <array>
                <string>_</string>
                <string>_</string>
            </array>
            <array>
                <string>*</string>
                <string>*</string>
            </array>
```

**Comment by eksperimental** [comment]
Note: I'm using  Sublime text 3

**Comment by josevalim** [comment]
Closing this as it has been stale for a while and it can lead to false positives, even if we considering only heredocs.
