### ISSUE TITLE
Format file keybinding conflicts with default

### ISSUE THREAD

**Issue by mwean** [elixir-editors/elixir-tmbundle#136]
Hi, it looks like the new update that includes a keybinding for the format file command conflicts with the default "Slurp Find String" keybinding.

**Slurp Find String**
> Copies the current selection or word into the “find” field of the find panel.

I think it might make sense to use another keybinding for your command, since it was very surprising when this happened, and it was tough to find out which package was causing it.

For others that want to override it, just add the following to your User keymap:

```json
{
  "keys": ["super+e"],
  "command": "slurp_find_string"
}
```

**Comment by josevalim** [comment]
I agree. I will fix it. :)
