### ISSUE TITLE
No highlighting/snippet for @typedoc, no highlighting for @moduledoc

### ISSUE THREAD

**Issue by evadne** [elixir-editors/elixir-tmbundle#152]
As subject.

**Comment by josevalim** [comment]
@evadne this is what i get:

![screen shot 2018-07-19 at 11 56 03](https://user-images.githubusercontent.com/9582/42935741-be21d1a2-8b4a-11e8-83e4-910d240528db.png)

Are you seeing something different?

**Comment by xtian** [comment]
I also get correct highlighting for `@typedoc` and `@moduledoc`. IMO this can be closed.
