### ISSUE TITLE
Continuous testing of the grammar

### ISSUE THREAD

**Issue by michalmuskala** [elixir-editors/elixir-tmbundle#153]
We should find a solution for continuous testing of the grammar, so that a situation like https://github.com/github/linguist/issues/4203 does not happen again.

For ideas see: https://github.com/github/linguist/issues/4203#issuecomment-406562967

**Comment by nixel2007** [comment]
Also you can use original ST3 testing tools - https://www.sublimetext.com/docs/3/syntax.html#testing

don't hesitate to ping me for any info or help.

**Comment by josevalim** [comment]
In master! Thanks @nixel2007 for the points, really helpful.

This repository is also great: https://github.com/SublimeText/UnitTesting
