### ISSUE TITLE
Auto-formatting within a monorepo

### ISSUE THREAD

**Issue by xtian** [elixir-editors/elixir-tmbundle#158]
I work on a couple projects with multiple discrete Elixir apps in top-level directories in a single git repo. These apps are deployed independently and there are other kinds of apps as well (e.g., JS) so an umbrella project isn't appropriate.

Usually I will open the top-level directory in Sublime so I can easily work and search across apps, however the current `mix format` integration breaks in this case as there is no `mix.exs` or `.formatter.exs` at this location.

So: it would be great if the path to the file passed to `mix format` was recursively descended until a `mix.exs` was found. I'm happy to put together a PR for this functionality if that solution is considered appropriate.

Thanks!

**Comment by josevalim** [comment]
@xtian this is supported in Elixir itself. The trick is to use the subdirectories feature of the formatter. Make sure you are running on Elixir v1.7 and add this as the `.formatter.exs` in your umbrella root:

```elixir
# Used by "mix format"
[
  inputs: ["mix.exs", "config/*.exs"],
  subdirectories: ["apps/*"]
]
```

This way each umbrella child can keep its formatter identity and the umbrella root just delegates to it.

**Comment by xtian** [comment]
@josevalim This is specifically not in an umbrella app context so there is no root-level `mix.exs`

**Comment by josevalim** [comment]
This technique should work even without an umbrella app. IIRC the formatter does not care about mix.exs. Have you tried it?

**Comment by xtian** [comment]
Yes. We use `import_deps` so we get this error:

```
* (Mix) Unknown dependency :ecto given to :import_deps in the formatter configuration. The dependency is not listed in your mix.exs for environment :dev
```

**Comment by josevalim** [comment]
Oh, good catch on the import_deps. Makes sense then, feel free to send a PR
that allows this issue to be addressed. :)
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
