### ISSUE TITLE
Regression in binary (string) interpolation tokenizer (Sublime Text 3)

### ISSUE THREAD

**Issue by tompave** [elixir-editors/elixir-tmbundle#161]
I think that [this change](https://github.com/elixir-editors/elixir-tmbundle/pull/155/files?utf8=%E2%9C%93&diff=unified&w=1#diff-3f0dec95dce97e31610d965d56e42acdL1358) introduced a regression in the binary interpolation syntax: `"#{}"`. It also affects heredocs (`"""`) and sigils (`~w` and `~s`, e.g. `~w(foo #{1+1})`). This is happening on Sublime Text 3 on macOS.

(I noticed this yesterday even though it looks like the PR was merged in August. I'm not sure if Sublime/PackageControl hadn't updated this package until a few days ago, or if recently I've just not written enough Elixir to notice earlier.)

I have configured my own color scheme to highlight Elixir in a way consistent with Ruby. For example, this snippet contains some Elixir code highlighted as Ruby, to illustrate how Sublime has usually highlighted Elixir before this regression:

<img width="754" alt="ruby" src="https://user-images.githubusercontent.com/2141406/48844025-ae4aa080-ed90-11e8-8d35-e9dbde4584a0.png">

With the regression, I now see this:

<img width="754" alt="elixir" src="https://user-images.githubusercontent.com/2141406/48844050-c15d7080-ed90-11e8-9927-d5962197f961.png">

In the past, when this `elixir-tmbundle` package introduced breaking changes I would just update my color scheme to match the new tokenization. This time I can't because of an issue with the closing `}` character.

The next four screenshots illustrate the language scopes that the tokenizer is assigning.

<img width="769" alt="open" src="https://user-images.githubusercontent.com/2141406/48844193-0aadc000-ed91-11e8-9c58-a67f0cdbb0c6.png"><img width="769" alt="close" src="https://user-images.githubusercontent.com/2141406/48844201-0f727400-ed91-11e8-9442-486c9f9da460.png"><img width="769" alt="close_wrong" src="https://user-images.githubusercontent.com/2141406/48844202-113c3780-ed91-11e8-841e-91af770f042a.png"><img width="768" alt="screenshot 2018-11-21 at 13 28 09" src="https://user-images.githubusercontent.com/2141406/48844316-58c2c380-ed91-11e8-803e-b94859878d41.png">

The new bits are the `begin` and `end` in `punctuation.section.embedded.begin.elixir`. That is fine, I can just update the color scheme to deal with those. The problems are:

1. The closing `}` character is tokenized with a further scope: `source.elixir`. It's being treated as source code.
2. When the interpolation block `#{}` contains something that ends with `}` (for example a tuple), then the closing `}` of the tuple will be used as end of the interpolation block, and the actual closing `}` will not be tokenized at all, and treated as part of the string.

With these two issues fixed, I will be able to update my color scheme.

While I'm opening this issue to report the regression, I'd also like to ask why https://github.com/elixir-editors/elixir-tmbundle/pull/155 had to introduce so many breaking changes (the PR doesn't say). Was it to ensure compatibility with the latest TextMate 2? A quick Google search suggests that today Sublime Text is widely more used than TextMate (1 or 2), so I wonder if introducing so many syntax definition changes is worth it and if they can be rolled back.

If they can't, and this issue can't be fixed, I suppose that another option would be to stop managing this package with [Package Control](https://packagecontrol.io/packages/Elixir) and just install it manually with git, and target the [`tm1` tag](https://github.com/elixir-editors/elixir-tmbundle/releases/tag/tm1), that points to the latest commit before https://github.com/elixir-editors/elixir-tmbundle/pull/155 was merged.

**Comment by josevalim** [comment]
Hi @tompave! Thanks for the detailed report.

I would honestly like this to support both editors, even if it means it is suboptimal for both, because I don't think we have enough bandwidth to maintain both. That said, I am glad to revert the definitions so they work with the examples you mentioned above, I just don't how much work it is.

Is it something you would be interested in sending a PR for? Thank you!

**Comment by tompave** [comment]
Hi @josevalim, thank you for the quick reply!

> That said, I am glad to revert the definitions so they work with the examples you mentioned above,
> (...)
> Is it something you would be interested in sending a PR for?

I can give it a go, but possibly not this week. Also, if the other changes make sense, I'd rather try to "roll forward" if I can rather than rolling back everything. I'm just not familiar enough with the `tmLanguage` syntax to evaluate it on my own.

---

One correction on what I wrote initially:

> The problems are:
> 1. The closing } character is tokenized with a further scope: source.elixir. It's being treated as source code.
>
> (...)
> With these two issues fixed, I will be able to update my color scheme.

Technically, I can make it work even if issue `1` is not fixed. I can just consider the extra `source.elixir` scope. I'm reporting it mainly because it seems wrong to apply that extra scope to the closing brace.

**Comment by josevalim** [comment]
That makes sense. We can also bring @infininight in if we have any questions.

**Comment by tompave** [comment]
Ok, thanks. I'll give it a stab by next week.

**Comment by tompave** [comment]
Hi @josevalim, apologies for the late reply.

I've finally found the time to give this a go, but I haven't been successful, sorry.

I've tried to modify the XML of the `Elixir.tmLanguage` plist, but I couldn't resolve the issues. I've tried to revert the changes to the `interpolated_elixir` dictionary, to remove the `begin` and `end` from `punctuation.section.embedded.begin.elixir`, and revert it to `punctuation.section.embedded.elixir`, but there are too many other changes in that PR that alter the behaviour of the syntax definition.

Specifically, I haven't been able to resolve this issue:

```
"foo #{inspect %{ok: 1}} bar"
                      ^^
                      12
```
Where `}` number 1 is seen as the end of the `#{}` interpolation sequence, and `}` number 2 is seen as simply part of the string. This is not a big deal for people that use a default Sublime colour scheme that doesn't highlight them anyway (for example, Monokai: [img](https://user-images.githubusercontent.com/2141406/49698942-93ff2800-fbc2-11e8-97bf-6c6c46295492.png)), but as I mentioned in the first post it's a bit of a pain for colour schemes that do (e.g. mine, with the [old version](https://user-images.githubusercontent.com/2141406/49698967-ef311a80-fbc2-11e8-9469-ec5710bafc50.png) of this package, and with [the current one](https://user-images.githubusercontent.com/2141406/49698973-f2c4a180-fbc2-11e8-841f-da8ac189b7bb.png)). Also, as I've also mentioned in the opening post, while I can update my colour scheme to match the new syntax scopes (with the `begin` and `end` fragments), I can't do much to deal with the fact that the closing `}` is not identified correctly. (I've tried)

Before spending more time on this, I think I would need some pointers from @infininight if they're available, because I've found reading the XML diff quite frustrating. It's no one's fault, as XML is XML after all, but the documentation is a bit lacking. The docs for TextMate 2 are empty, only the [old docs for TextMate 1 are available](https://macromates.com/manual/en/language_grammars), and they seem to not match what we use today. They mention an "old style property list syntax" that is not XML, and all the examples seem to use this non-XML syntax.

More in general, in https://github.com/elixir-editors/elixir-tmbundle/pull/155 @infininight mentioned:

> (...) review this bundle for inclusion in the bundle installer for TextMate. Had a few changes that I came across during the review that I've fixed up.
> (...)
> Due to a grammar and scoping features I used the grammar is no longer compatible with TextMate 1.x. While usage of 1.x is very low now it would be good to create a tag for a compatible version before pulling in the changes.

And I was wondering if all these `tmLanguage` changes are really necessary (e.g. what are the benefits? Consistency with some standard scope names?), and I would like to understand if incompatibility with TextMate 1.x also means incompatibility with Sublime Text 2/3. [These are the ST docs](http://docs.sublimetext.info/en/latest/reference/syntaxdefs.html), for reference.

I'm asking because I've found [comments that suggest](https://forum.sublimetext.com/t/isnt-it-the-time-to-move-from-tmtheme-format-to-a-yaml-based-color-scheme-definition/20194/2) that a lot of the new files that that PR added are TextMate only and that SublimeText will ignore them.

For the moment I've found it easier to just go back to the `tm1` tag to use the old version of this package, that still looks great. If my suspicion of incompatibility with Sublime Text is confirmed, I wonder if it wouldn't be better to just backport there some of the other recent changes on `master`.

**Comment by tompave** [comment]
To clarify, just reverting the syntax definitions seem to work, but I don't know if it breaks any of the TextMate-only files:

```
cd elixir-tmbundle
git checkout master && git pull
git checkout tm1 -- Syntaxes/
cp -fR . "$HOME/Library/Application Support/Sublime Text 3/Packages/FixedElixirPackage"
```

**Comment by tompave** [comment]
Hello, I was wondering if @infininight has had a look at this issue and has any pointers.
