### ISSUE TITLE
mix_format_on_save causes formatter to run on EEx templates in SublimeText

### ISSUE THREAD

**Issue by tarzan** [elixir-editors/elixir-tmbundle#163]
I installed the package for SublimeText 3 and configured the preferences as:
```json
{
  "mix_format_on_save": true,
  "reload_after_mix_format": true
}
```

Now, whenever I save an HTML(EEx) template the `mix format` task is being run on this file. I would either expect this file type to be excluded by the formatter config file or by the run command in the python script. The former is (presumably) by design and the latter goes wrong here:
https://github.com/elixir-editors/elixir-tmbundle/blob/c7e1a4504f8eb815e45e1ab0894ee5c5001bfc52/mix_format_file.py#L19
as it matches these in the EEx templates:
https://github.com/elixir-editors/elixir-tmbundle/blob/c7e1a4504f8eb815e45e1ab0894ee5c5001bfc52/Syntaxes/EEx.tmLanguage#L43
and EEx tags are being supported in the HTML templates since https://github.com/elixir-editors/elixir-tmbundle/commit/36aa122a7fa141876bdcbd00bd71195544a0ee52

**Comment by tarzan** [comment]
Any suggestions on how to fix this? I am willing to put some work in it :)

**Comment by tarzan** [comment]
Would #164 be an acceptable fix?

**Comment by florish** [comment]
@tarzan Thanks for the work on #164! I ran into the same problem in Sublime Text 3 and hoped to have found a fix...

Unfortunately, after pulling the latest version from master, the problem is still there for HTML (EEx) templates. Did #164 indeed resolve this issue for you?

To be sure, on save, I get errors like this in the Sublime console:

```
mix format failed for file: path/to/template.html.eex
** (SyntaxError) path/to/template.html.eex:1: syntax error before: '<'
    (elixir) lib/code.ex:538: Code.format_string!/2
    (mix) lib/mix/tasks/format.ex:397: Mix.Tasks.Format.format_file/2
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by tarzan** [comment]
Ah! I seems you are right, I was testing with false positives 'cause it didn't read my settings override of `format_on_save: true`. So, yes I still have the same issue. I did manage to fix it though: https://github.com/tarzan/elixir-tmbundle/commit/d006a4a53ad84749a54e51e728efc0ccec197a22

**Comment by tarzan** [comment]
@josevalim can you re-open this issue?

**Comment by josevalim** [comment]
Done! Can you please send a new PR? Or should I revert the previous one?

**Comment by tarzan** [comment]
I created a new PR. Feel free to roll back the previous PR and/or rebase, I rebased mine on your current master.
