### ISSUE TITLE
`length` and similar keywords should not be highlighted

### ISSUE THREAD

**Issue by hauleth** [elixir-editors/elixir-tmbundle#169]
For the reasoning see elixir-editors/vim-elixir#431.

**Comment by josevalim** [comment]
I don't quite agree. It is worth highlighting what is allowed in guards. Sure, there are custom guards but they are macros. The functions that are allowed in guards are very special and pre-defined, so I would continue highlighting them. :+1:

**Comment by hauleth** [comment]
The problem is that this cause problems in highlighting:

![zrzut ekranu 2018-12-28 17 52 54](https://user-images.githubusercontent.com/291639/50522106-7fc79000-0ac9-11e9-8d03-fdb2f62f1ec6.png)

Here `length` isn't the same as `length/1` but is coloured anyway.

I believe that unless this list could be configured by user then it shouldn't match such values.

**Comment by josevalim** [comment]
Then maybe we could improve the keyword detection so it doesn’t get
variables. Probably by requiring a space or a parens after it.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by hauleth** [comment]
@josevalim it will not work in case of `foo |> length`

**Comment by josevalim** [comment]
Rght, so in face of all possible trade-offs, we need to pick something. I am fine with things as is. :)
