### ISSUE TITLE
Make mix format command preferencable to be docker compatible.

### ISSUE THREAD

**Issue by augnustin** [elixir-editors/elixir-tmbundle#175]
Since my app is hosted in a docker, in order to execute the formatting, I need to run: `docker-compose run app mix format`. 

I'd like to bind it to the Sublime package to execute it on save. Is there a way to make the `mix format` parameterable, so I can edit it to my own version?

Cheers

**Comment by josevalim** [comment]
I don't how to do that but if you know or if you figure it out, a PR would be appreciated!
