### ISSUE TITLE
Add syntax support for Phoenix LiveView templates

### ISSUE THREAD

**Issue by zwippie** [elixir-editors/elixir-tmbundle#177]
It would be nice to have syntax support for `.html.leex` files, the file extension used by [Phoenix LiveView](https://github.com/phoenixframework/phoenix_live_view) templates.

It's the same syntax as regular HTML (EEx) files, so the solution would be a one-liner in `/Syntaxes/HTML (EEx).tmLanguage` by adding `<string>html.leex</string>` to the `fileTypes` array.

I can make a PR if you want.

**Comment by josevalim** [comment]
Yess, PR please!
