### ISSUE TITLE
Excited to present revamped syntax highlighting

### ISSUE THREAD

**Issue by azizk** [elixir-editors/elixir-tmbundle#188]
Hi, Jośe!

Since I work daily with Elixir and Sublime Text, I was curious to see if I could improve the syntax highlighting definition.

I was aware of this package here, but honestly, I couldn't imagine working on regular expressions in an XML file. I decided to work on @princemaple's project instead. On occasion I made little contributions to it, but last October I began to work on a full rewrite. I completed the effort a few weeks ago and now I'm pleased to present it to a wider audience. Check out the [changelog](https://github.com/princemaple/elixir-sublime-syntax/blob/master/CHANGELOG.md#v200--2021-04-27) for a near-complete list of all the new features.

So my next goal would be to get this shiny thing out to many more developers. I don't know how much sense it would make to try and merge the changes into this package. Maybe it would be as simple as replacing the old definitions with the new ones. It's totally fine if you want to leave it as is. However, I'd be very much interested in trying to get our files into Sublime Text itself as an integrated package. With your official stamp of approval we might have a better chance at achieving that. What do you think?

Hope you enjoy the new look&feel!

**Comment by josevalim** [comment]
Hi @azizk! We had this discussion in the past and I believe the main reason for not merging is because the XML files also work for Textmate. Is there any way we can keep Textmate compatibility? Thank you for your work!

**Comment by azizk** [comment]
Yes, I saw that PR, but I'm not necessarily trying to do the same. I believe if someone were keen on translating my work to Textmate's XML format then perhaps they could achieve that in one or two weekends. Provided there is a good tool for automatic translation and provided the (Oniguruma) regular expressions I wrote are compatible with the engine used in TM. I didn't use any of the new features from ST4, but still some effort will be required. It should be worth it considering how much stuff I implemented and how accurate it is. If someone is willing to do the bulk of the work I can offer some time to assist and help with regexps or answering questions.

So yeah, making my work compatible with Textmate is probably possible but maybe I'm underestimating how much needs to be done. Just curious, but is TM actively developed and how does it compare to Sublime Text 4 at the moment? Have you tried ST4 on your Mac yet?

Sublime Text has a [repo for all of its default packages](https://github.com/sublimehq/Packages). That's where I'd like to get the new package accepted. I haven't created a ticket in the issue tracker yet, because I think your support would make a difference. :)

**Comment by josevalim** [comment]
Oh, I see! What happens if both your package and this package are installed? Which one "wins"?

In any case, I am :+1: with adding your version upstream. Syntax additions to the language are very rare, so we should be fine. Just make sure you handle stepped ranges (basically the `//` in `x..y//z`) as well as `defn` and `defnp` from Nx properly. :)

**Comment by princemaple** [comment]
In Sublime I believe if a native syntax definition (`.sublime-syntax`) exists, it'd be preferred by the editor. It's easily customizable though. Users can choose to always use another syntax definition.

**Comment by azizk** [comment]
Don't worry, José, I added those as soon as they made an appearance. :wink: :+1:

So I tried it out but the other way around. ElixirSyntax was already installed and I added elixir-tmbundle next to it. Nothing major happens. You can choose any syntax definition and both are named "Elixir" (via the View menu, the status bar or command palette). ST remembers the path to the chosen syntax in the session file, so all the open files will stay on that syntax definition until you actively change it. But if you open new files it always uses my definition. Maybe it's because the native definition is preferred as princemaple suggested. At least it doesn't break anything afaics.

Thanks, José, for the support! Thanks for Elixir and all the tough work throughout all these years.
Here's to continued growth and success! :clinking_glasses:

**Comment by azizk** [comment]
Hey José!

As we talked at ElixirConf, the conclusion of trying to get the package into Sublime Text 4 is that it's not going to work out. The required changes would take an enormous amount of effort and they don't really warrant the imagined benefits. So ElixirSyntax is going to remain an external package as it is now.

Anway, v2.2.0 is out with support for HEEx and Surface! Here is my tweet if you'd like to share it on your feed to help make the package more known: :+1:
https://twitter.com/codingaziz/status/1439570753628876803

I guess we can close this ticket now.

**Comment by azizk** [comment]
Btw, maybe you'd like to link to ElixirSyntax in the README as an alternative package...

**Comment by josevalim** [comment]
Yes, a PR to update the README is very welcome!

**Comment by azizk** [comment]
Hi, @josevalim!

As I mentioned on the elixir-sublime-syntax [issue board](https://github.com/elixir-sublime/elixir-sublime-syntax/issues/45) I'd like to move that project under the elixir-editors umbrella. I think it's a better place for it to be here. What do you think? Can we do that? :slightly_smiling_face:

**Comment by josevalim** [comment]
Add me as an admin to the repo and I can transfer it (and remove myself as an admin).
