### ISSUE TITLE
Sublime Text 4 crashes due to saving Elixir files

### ISSUE THREAD

**Issue by liveforeverx** [elixir-editors/elixir-tmbundle#189]
I have fresh new installation of Sublime Text 4 (to verify, that it happens with Elixir plugin - so I'm not sure, it is problem of a plugin). The only package is installed is - Elixir.

Whenever I try to save any `.ex` File (doesn't happen with other files) - the Sublime crashes. I saw the same behaviour on fully installed Sublime and again only on Elixir files, so I tried to replicate with a fresh installation.

I do not know, how to retrieve logs to understand it more. Does anybody else has the same problem? Does anybody knows, how to debug it?

**Comment by josevalim** [comment]
Do you have format on save or similar? It may be related to #166.

**Comment by liveforeverx** [comment]
@josevalim That was the first thing, which I tried, I disabled in old installation, but it happens without format on save.

Now, I have installed package additionally manually, to try to find the error, and I have this lines added:

<img width="536" alt="Screenshot 2021-06-05 at 17 36 36" src="https://user-images.githubusercontent.com/660306/120897036-97a18780-c624-11eb-9b61-d44bd0c568b7.png">

For existing files I see this:

<img width="269" alt="Screenshot 2021-06-05 at 17 37 11" src="https://user-images.githubusercontent.com/660306/120897052-ab4cee00-c624-11eb-9616-57d1f4c2fd20.png">

So, it it isn't enabled.

**Comment by liveforeverx** [comment]
I tried to install some non-standard syntax highlighting (for example: Julia) - saving new files with `.jl` extension doesn't crash Sublime.

**Comment by liveforeverx** [comment]
I could reproduce it with other files (it just happens not always). So, it isn't related to Elixir.

Sorry for bothering! I'm closing it now. Thank you for very quick answer!

Will try to open by Sublime.
