### ISSUE TITLE
Plugin creates folders when typing File.mkdir

### ISSUE THREAD

**Issue by rekyuu** [elixir-editors/elixir-tmbundle#92]
If I type the line `File.mkdir("tmp")` in Sublime 3, it will make said directory in the working directory of the file.

After some testing, it also happens with `File.touch` and I'm sure a few others.

[Here's a video.](https://kyo.li/v/aflp.webm)

**Comment by josevalim** [comment]
Are you sure it is this project and not https://github.com/vishnevskiy/ElixirSublime ?

**Comment by rekyuu** [comment]
You know, I posted there first and thought the same thing. Turns out I had both installed. However, I did remove ElixirSublime package and the issue persisted with this Elixir package.

**Comment by josevalim** [comment]
Thank you. I don't think there is anything on this package that evaluates
code. Did you reinstall sublime and the problem still persists? Help is
appreciated to find the source!

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
Please let us know if this is still up to date, I could not reproduce the issue.
