### ISSUE TITLE
Closing binary file does not get colored when using typespecs

### ISSUE THREAD

**Issue by cesarvargas00** [elixir-editors/elixir-tmbundle#99]
Like so:
<img width="341" alt="captura de tela 2016-03-29 as 01 23 44" src="https://cloud.githubusercontent.com/assets/742797/14097912/e91e2c2a-f54c-11e5-8334-951a0780d808.png">

**Comment by princemaple** [comment]
Actually, the whole binary highlighting is broken... There is no matching starting `<<` at all.

**Comment by josevalim** [comment]
PR please?
